// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dunamu_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DunamuModel _$DunamuModelFromJson(Map<String, dynamic> json) => DunamuModel(
      code: json['code'] as String,
      currencyCode: json['currencyCode'] as String,
      currencyName: json['currencyName'] as String?,
      country: json['country'] as String?,
      name: json['name'] as String?,
      date: json['date'] as String,
      time: json['time'] as String,
      recurrenceCount: json['recurrenceCount'] as int,
      basePrice: (json['basePrice'] as num).toDouble(),
      openingPrice: (json['openingPrice'] as num).toDouble(),
      highPrice: (json['highPrice'] as num).toDouble(),
      lowPrice: (json['lowPrice'] as num).toDouble(),
      change: json['change'] as String,
      changePrice: (json['changePrice'] as num).toDouble(),
      cashBuyingPrice: (json['cashBuyingPrice'] as num).toDouble(),
      cashSellingPrice: (json['cashSellingPrice'] as num).toDouble(),
      ttBuyingPrice: (json['ttBuyingPrice'] as num).toDouble(),
      ttSellingPrice: (json['ttSellingPrice'] as num).toDouble(),
      tcBuyingPrice: (json['tcBuyingPrice'] as num?)?.toDouble(),
      fcSellingPrice: (json['fcSellingPrice'] as num?)?.toDouble(),
      exchangeCommission: (json['exchangeCommission'] as num).toDouble(),
      usDollarRate: (json['usDollarRate'] as num).toDouble(),
      high52wPrice: (json['high52wPrice'] as num).toDouble(),
      high52wDate: json['high52wDate'] as String,
      low52wPrice: (json['low52wPrice'] as num).toDouble(),
      low52wDate: json['low52wDate'] as String,
      currencyUnit: json['currencyUnit'] as int,
      provider: json['provider'] as String?,
      timestamp: json['timestamp'] as int,
      id: json['id'] as int,
      createdAt: json['createdAt'] as String,
      modifiedAt: json['modifiedAt'] as String,
      signedChangeRate: (json['signedChangeRate'] as num).toDouble(),
      signedChangePrice: (json['signedChangePrice'] as num).toDouble(),
      changeRate: (json['changeRate'] as num).toDouble(),
    );

Map<String, dynamic> _$DunamuModelToJson(DunamuModel instance) =>
    <String, dynamic>{
      'code': instance.code,
      'currencyCode': instance.currencyCode,
      'currencyName': instance.currencyName,
      'country': instance.country,
      'name': instance.name,
      'date': instance.date,
      'time': instance.time,
      'recurrenceCount': instance.recurrenceCount,
      'basePrice': instance.basePrice,
      'openingPrice': instance.openingPrice,
      'highPrice': instance.highPrice,
      'lowPrice': instance.lowPrice,
      'change': instance.change,
      'changePrice': instance.changePrice,
      'cashBuyingPrice': instance.cashBuyingPrice,
      'cashSellingPrice': instance.cashSellingPrice,
      'ttBuyingPrice': instance.ttBuyingPrice,
      'ttSellingPrice': instance.ttSellingPrice,
      'tcBuyingPrice': instance.tcBuyingPrice,
      'fcSellingPrice': instance.fcSellingPrice,
      'exchangeCommission': instance.exchangeCommission,
      'usDollarRate': instance.usDollarRate,
      'high52wPrice': instance.high52wPrice,
      'high52wDate': instance.high52wDate,
      'low52wPrice': instance.low52wPrice,
      'low52wDate': instance.low52wDate,
      'currencyUnit': instance.currencyUnit,
      'provider': instance.provider,
      'timestamp': instance.timestamp,
      'id': instance.id,
      'createdAt': instance.createdAt,
      'modifiedAt': instance.modifiedAt,
      'signedChangeRate': instance.signedChangeRate,
      'signedChangePrice': instance.signedChangePrice,
      'changeRate': instance.changeRate,
    };
